### PR TITLE
More helpful panic message on invalid/unknown XML

### LINKED ISSUE #40: Print helpful error on deserialization error
There are some users reporting errors on "malformed" (i.e. in the sense of: unknown format) input, e.g. [#32](https://github.com/jfrimmel/cargo-valgrind/issues/32#issuecomment-806323478). Currently (version `2.0.0`) the tool panics:
```bash
$ cargo valgrind run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `/home/jfrimmel/.cargo/bin/cargo-valgrind target/debug/ffi-bug`
Test
thread 'main' panicked at 'Cannot parse valgrind output: Error(Custom("missing field `xwhat`"), State { next_error: None })', src/main.rs:69:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This is really unfortunate. This error should be handled gracefully, as it was done in the `1.x` version. But instead of only writing, that there is an error, a more helpful output would be:

```
$ cargo valgrind run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `/home/jfrimmel/.cargo/bin/cargo-valgrind target/debug/ffi-bug`
Test

Internal error in `cargo valgrind`: encountered an unknown valgrind output.
Below you'll find the output of valgrind. It would be appreciated, if you create a bug-report using this output at 
https://github.com/jfrimmel/cargo-valgrind/issues/new
```

### PR DESCRIPTION
**Pull request by jfrimmel**
If the valgrind binary outputs anything, that `cargo-valgrind` cannot handle, there is an error output.
# Current state
Currently, that output looks like that:
```
error: unexpected valgrind output: custom: 'missing field `auxwhat`'
```
This looks like the run binary had an error or something. It is not immediately obvious, that there is an implementation error in `cargo-valgrind`.

# Proposed output
This PR changes the error output to a panic with a custom message:
```
Oooops. cargo valgrind unexpectedly crashed. This is a bug!

This is an error in this program, which should be fixed. If you can, please submit a
bug report at

    https://github.com/jfrimmel/cargo-valgrind/issues/new/choose

To make fixing the error more easy, please provide the information below as well as
additional information on which project the error occurred or how to reproduce it.

cargo-valgrind: version 2.0.1
XML format mismatch between `valgrind` and `cargo valgrind`: custom: 'missing field `auxwhat`'
XML output of valgrind:
<the XML content/>
```
Using this output, the user knows clearly, that there is a bug and that should be reported.

Fixes #40.

### CODE REVIEW

File: src/valgrind/mod.rs [hunk 1]
```diff
@@ -2,10 +2,10 @@
 
 pub mod xml;
 
-use std::fmt;
 use std::net::{SocketAddr, TcpListener};
 use std::process::Command;
 use std::{ffi::OsStr, process::Stdio};
+use std::{fmt, io::Read};
```
Comment (jfrimmel) [inline src/valgrind/mod.rs:8]: This formatting change was not intended, but can be kept (or changed back the next time).
```suggestion
use std::fmt;
use std::io::Read;
```
